---
- name: Configure host.
  hosts: localhost

  vars_files:
    - vars/dock.yml
    - vars/dotfiles.yml
    - vars/general.yml
    - vars/homebrew.yml
    - vars/mas.yml
    - vars/oh-my-zsh.yml
    - vars/pip.yml
    - vars/sudoers.yml
    - vars/terminal.yml

  pre_tasks:
    - name: Assert that variables are set
      ansible.builtin.assert:
        that:
          - mas_email != ""
          - mas_password != ""
      when: mas_installed_apps | length > 0
      tags: ["preflight"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
#    - role: geerlingguy.mac.mas
#      when: mas_installed_apps or mas_installed_app_ids
#      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']
    
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/oh-my-zsh.yml
      tags: ["oh-my-zsh"]

    - import_tasks: tasks/astro-vim.yml
      tags: ["astro-vim"]
